### ISSUE TITLE
ic-styled issue on 1.8.0-beta.1

### ISSUE THREAD

**Issue by seifsallam** [instructure/ic-autocomplete#27]
After updating to latest Ember beta (1.8.0), ic-autocomplete stopped working completely. Can you please confirm if this is an `ic-autocomplete/styled` issue or Ember's issue?

Error output 

```
TypeError: undefined is not a function
    at null.injectStyles (http://0.0.0.0:4200/assets/vendor.js:100687:32)
    at applyStr (http://0.0.0.0:4200/assets/vendor.js:32458:34)
    at sendEvent (http://0.0.0.0:4200/assets/vendor.js:27587:13)
    at __exports__.default.Mixin.create.trigger (http://0.0.0.0:4200/assets/vendor.js:44582:9)
    at apply (http://0.0.0.0:4200/assets/vendor.js:32447:27)
    at superFunction [as _super] (http://0.0.0.0:4200/assets/vendor.js:28919:15)
    at EmberObject.extend.trigger (http://0.0.0.0:4200/assets/vendor.js:53585:21)
    at apply (http://0.0.0.0:4200/assets/vendor.js:32447:27)
    at superWrapper [as trigger] (http://0.0.0.0:4200/assets/vendor.js:32024:15)
    at EmberRenderer.Renderer.willInsertElement (http://0.0.0.0:4200/assets/vendor.js:52140:32)
    at EmberRenderer.Renderer_renderTree [as renderTree] (http://0.0.0.0:4200/assets/vendor.js:23775:18)
    at Object.merge.ensureChildrenAreInDOM (http://0.0.0.0:4200/assets/vendor.js:53480:22) 
```

Source of the issue

``` js
Ember.Component.reopen({
    injectStyles: function() {
      var klass = this.constructor;
      var Style = lookupStyleComponent(this);
      if (!Style || Style._injected) { return; }
      Style._injected = true;
      var name = getStyleComponentName(this);
      var css = Style.create().renderToBuffer().buffer; // <<< This line
      inject(name, css);
    }.on('willInsertElement')
  });
```

**Comment by ryanflorence** [comment]
fixed by f730fee5af72a41f01a434095a40856ec97f8e7e
