### ISSUE TITLE
upgrade to handlebars 2

### ISSUE THREAD

**Issue by shaunc** [instructure/ic-autocomplete#31]
I am not able to use with ember 1.9 which requires handlebars 2.0. When I manually require handlebars 2.0 inside of broccoli-template-compiler/ember-template-compiler, I get an error trying to build:

Any suggestions?

```
$ broccoli build dist
    File: templates/autocomplete-css.js
    Error: Line 2: Unexpected identifier
        at throwError (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2579:21)
        at throwUnexpected (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2623:13)
        at expect (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2650:13)
        at parseArrayInitialiser (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2783:21)
        at parsePrimaryExpression (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:3076:20)
        at /Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5661:38
        at trackLeftHandSideExpressionAllowCall (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5563:61)
        at parsePostfixExpression (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:3214:20)
        at /Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5661:38
        at parseUnaryExpression (/Volumes/Macintosh_HD/Users/shauncutts/src/other/ic-autocomplete/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:3278:16)

    Build failed
```

**Comment by shaunc** [comment]
In templates/autocomplete-css.js we have

```
import Ember from 'ember';
export default Ember.Handlebars.template([object Object]);
```

... so this isn't compiling correctly....

**Comment by abuiles** [comment]
@shaunc see #30 you can use my fork in the meantime, just add this to your bower  "ic-autocomplete": "abuiles/ic-autocomplete#htmlbars-build",

**Comment by shaunc** [comment]
Ah — great — thanks!

**Comment by shaunc** [comment]
@abuiles ... btw -- how should I include now?

I used to jave:

```
app.import('bower_components/ic-styled/main.js');
app.import('bower_components/ic-autocomplete/dist/globals/main.js');
```

in my Brocfile; then I could include via:

```
import Autocomplete from 'sheetweaver/components/ic-autocomplete'
```

(where "sheetweaver" is my app.) This seemed a bit odd, as the ember-cli doc said that globals would simply be available as globals (I assume component was registering itself internally somehow). Now, however, this doesn't seem to work -- the import fails. Also "Autocomplete" is not in the global namespace.

Any hints? :) ... (e.g. if I use the AMD version, what should I export?)

UPDATED (to answer my own question): 

after this:

```
app.import('bower_components/ic-autocomplete/dist/globals/main.js');
```

autocomplete is available as:

```
ic.autocomplete.AutocompleteComponent
```

I don't know how/why it was working before with the "import", but now am all set with the global.
